language: python

python:

  - "3.6-dev"

install:

  - pip install -r requirements.txt
  - pip install coveralls

script:

 - python -m pytest --cov-report term-missing --cov=app
 
after_success:

  - coveralls
  -  coverage xml