language: python

python:

  - "3.6-dev"

install:

  - pip install -r requirements.txt

script:

 - py.test tests/ --doctest-modules --pep8 coveralls -v --cov tests --cov-report term-missing
 
after_success:

  - tests