language: python

python:

  - "3.6-dev"

install:

  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  

script:

 - python -m pytest --cov-report term-missing
 
after_success:

  - coveralls
  -  coverage xml