language: python

python:

  - "3.6-dev"

install:

  - pip install -r requirements.txt
  - pip install coveralls codecov 
  

script:

 -  python -m pytest 
 
after_success:

  - coveralls
  -  coverage xml
  - codecov --token=8e190961-0d12-463e-9385-c7bb0de21426
  